package controller;

import java.util.UUID;
import server.ClientState;
import server.IProtocolHandler;
import xml.Message;


public class ConnectToDLEController implements IProtocolHandler{


	public ConnectToDLEController(){

	}
	
	//TODO Not sure where we are storing this ID, if at all, or if
	// it is just expected that the user will store this and
	//have it contained in all future messages?
	//xml document just states "unique ID is generated by server and used there"
	
	/**A connectRequest Message contains only 'connectRequest' and 
	 * ConnectToDLEController.process returns a response containing 
	 * unique ID for communication with the server.
	 * @author Brendan
	 */
	@Override
	public synchronized Message process(ClientState state, Message request) {
		// Initialize local variables
		Message response = null;
		
		//Needs a new unique ID for the client
		String uniqueID = UUID.randomUUID().toString();
		String xmlResponse = new String("<?xml version='1.0' encoding='UTF-8'?>" +
				"<response version='1.0' id='" + uniqueID + "'>" +
				"  <complexType>" +
				"    <user name='admin' password='password' />" +
				"  </complexType>" +
				"</response>");
		response = new Message(xmlResponse);
		
		return response;
	}
}

