DROP TABLE IF EXISTS edge;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS choice;
DROP TABLE IF EXISTS administration;
DROP TABLE IF EXISTS event;

DROP PROCEDURE IF EXISTS procUpdateEvent;
DROP PROCEDURE IF EXISTS procUpdateUser;
DROP PROCEDURE IF EXISTS procUpdateChoice;
DROP PROCEDURE IF EXISTS procUpdateEdge;
